// File generated by `flutterfire configure`.
// This is a temporary stub. Run `flutterfire configure` to generate the proper configuration.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_INSERT_YOUR_ANDROID_API_KEY_HERE',
    appId: '1:INSERT_PROJECT_NUMBER:android:INSERT_YOUR_APP_ID',
    messagingSenderId: 'INSERT_PROJECT_NUMBER',
    projectId: 'INSERT_YOUR_PROJECT_ID',
    storageBucket: 'INSERT_YOUR_PROJECT_ID.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_INSERT_YOUR_IOS_API_KEY_HERE',
    appId: '1:INSERT_PROJECT_NUMBER:ios:INSERT_YOUR_IOS_APP_ID',
    messagingSenderId: 'INSERT_PROJECT_NUMBER',
    projectId: 'INSERT_YOUR_PROJECT_ID',
    storageBucket: 'INSERT_YOUR_PROJECT_ID.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_INSERT_YOUR_WEB_API_KEY_HERE',
    appId: '1:INSERT_PROJECT_NUMBER:web:INSERT_YOUR_WEB_APP_ID',
    messagingSenderId: 'INSERT_PROJECT_NUMBER',
    projectId: 'INSERT_YOUR_PROJECT_ID',
    storageBucket: 'INSERT_YOUR_PROJECT_ID.appspot.com',
  );

  static FirebaseOptions get currentPlatform {
    return android;
  }
}
